version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/usr/src/app/src
    container_name: server
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 250M
    command: npm run dev
  redis:
    image: redis:alpine
    container_name: redis
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2"
    #       memory: 4GB
    ports:
      - "6379:6379"