version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/usr/src/app/src
    container_name: server
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 250M
    command: npm run dev